kind: Deployment
apiVersion: apps/v1
metadata:
  name: "{{ .Release.Name }}"
  labels:
    app: "{{ .Chart.Name }}"
    chart: "{{ .Chart.Name }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: "{{ .Chart.Name }}"
      release: "{{ .Release.Name }}"
      heritage: "{{ .Release.Service }}"
  template:
    metadata:
      name: "{{ .Release.Name }}"
      labels:
        app: "{{ .Chart.Name }}"
        chart: "{{ .Chart.Name }}"
        release: "{{ .Release.Name }}"
        heritage: "{{ .Release.Service }}"
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
          - containerPort: {{ .Values.port | default 8686 }}
            protocol: TCP
        command: ["grafana-reporter"]
        args: ["--grid-layout", "-ip", "{{ .Values.grafanaUrl }}","-port",":{{ .Values.port | default 8686 }}","-proto","http://"]
        resources:
{{ toYaml .Values.resources | indent 10 }}
